version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      frontend-build-tooling-major:
        patterns:
          - 'vite'
          - '@vitejs/plugin-vue'
        update-types:
          - 'major'
      frontend-test-tooling-major:
        patterns:
          - 'vitest'
          - '@vitest/coverage-v8'
        update-types:
          - 'major'
      frontend-runtime-major:
        patterns:
          - 'vue'
          - 'vue-router'
          - 'pinia'
        update-types:
          - 'major'
      linting-major:
        patterns:
          - 'eslint'
          - 'eslint-plugin-vue'
          - 'eslint-plugin-security'
        update-types:
          - 'major'
      backend-test-tooling-major:
        patterns:
          - 'mongodb-memory-server'
        update-types:
          - 'major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
